### ISSUE TITLE
Update Abbreviations

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/locations-app#66]
#### General changes
- [x] Don't use all caps for headings (Divisions / Subdivisions, Featured, Events, About / About the Division, Plan Your Visit Blogs, Exhibitions)

#### Hours box changes
- [x] Don't use all caps for Regular hours / Upcoming hours
- [x] Don't abbreviate days of the week

#### Events section
- [x] Don't abbreviate days of the week
- [x] It doesn't look like months are being abbreviated, but please double check

#### Blog section
- [x] It doesn't look like months are being abbreviated, but please double check

#### Exhibition section
- [x] It doesn't look like months are being abbreviated, but please double check

**Comment by gkallenberg** [comment]
For location hours, we're relying on the Refinery to relate the data to the Locations App via its API response. The days of the week are hard coded as abbreviations in the code. We'll need to update the Refinery code base to allow for either a selectable date format or just send the entire weekday name instead of just sending the abbreviated form.

**Comment by EdwinGuzman** [comment]
Yeah, right. Long term updating the API would be ideal. I'm currently just creating a function to map the short days to the longer day names. It'll be fine for now but I can make it compatible with both short or long names from the API so that update in the API will be seamless 🌮 . Sounds good?

**Comment by EdwinGuzman** [comment]
Breakdown of the Day/Month abbreviations on sections of the app:

* Days were abbreviated on: _(Note, days of the week come in the form of `Mon.`, `Tue.`, etc, with a period at the end of a 3 character value._
** Hours Table "Regular Hours" (MON, TUES, WED, etc)
** Hours Table "Upcoming Hours" (MON, TUES, WED, etc) 
** Events  (Mon, Tues, Wed, etc)
** 
* Months were abbreviated on:
** Events (Aug, Jan, etc)
** **Not** on Blogs. This is because Events are in the form of `Fri, Aug 3 | 6PM` whereas Blogs are in the form of `December 10, 2007`. They use different filters for displaying time.
** **Not** on Exhibitions.
